DROP TABLE IF EXISTS actor_affiliations CASCADE;
DROP SEQUENCE IF EXISTS actor_affiliations_id_seq;
DROP TABLE IF EXISTS actor_roles CASCADE;
DROP SEQUENCE IF EXISTS actor_roles_id_seq;
DROP TABLE IF EXISTS actor_types CASCADE;
DROP SEQUENCE IF EXISTS actor_types_id_seq;
DROP TABLE IF EXISTS actors CASCADE;
DROP TABLE IF EXISTS actors_events;
DROP SEQUENCE IF EXISTS actors_id_seq;
DROP TABLE IF EXISTS event_subtypes CASCADE;
DROP SEQUENCE IF EXISTS event_subtypes_id_seq;
DROP TABLE IF EXISTS event_types CASCADE;
DROP SEQUENCE IF EXISTS event_types_id_seq;
DROP TABLE IF EXISTS events;
DROP SEQUENCE IF EXISTS events_id_seq;
DROP TABLE IF EXISTS locations;
DROP SEQUENCE IF EXISTS locations_id_seq;
DROP TABLE IF EXISTS scandal_consequences;
DROP SEQUENCE IF EXISTS scandal_consequences_id_seq;
DROP TABLE IF EXISTS scandal_subtypes CASCADE;
DROP SEQUENCE IF EXISTS scandal_subtypes_id_seq;
DROP TABLE IF EXISTS scandal_types CASCADE;
DROP SEQUENCE IF EXISTS scandal_types_id_seq;
DROP TABLE IF EXISTS scandals;
DROP SEQUENCE IF EXISTS scandals_id_seq;
